### PR TITLE
Feature: PSR4 compatible

### LINKED ISSUE #43: Plugin does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0
I get the following warning message,please fix this to comply with Composer V2.0:

Class omz13\XMLSitemap located in ./site/plugins/kirby3-xmlsitemap/src/xmlsitemap.php does not comply with psr-4 autoloading standard.

It will not autoload anymore in Composer v2.0. in phar:///Applications/DevDesktop/tools/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

```
Deprecation Notice: Class omz13\XMLSitemap located in ./site/plugins/kirby3-xmlsitemap/src/xmlsitemap.php does not comply with psr-4 autoloading standard.
```
```
It will not autoload anymore in Composer v2.0. in phar:///Applications/DevDesktop/tools/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

### PR DESCRIPTION
**Pull request by ceesvanegmond**
Fixes #43

### CODE REVIEW

**Comment by macx** [comment]
@omz13 Please merge it. Easy task.

**Comment by MaluNoPeleke** [comment]
How to install it with Composer?
I added it as an additional repository but no luck:

composer.json:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/ceesvanegmond/kirby3-xmlsitemap"
        }
    ],
    "require": {
        "getkirby/composer-installer": "^1.1",
        "ceesvanegmond/kirby3-xmlsitemap": "^1.2.1",
```

**Comment by b0rt** [comment]
to use the fork of ceesvanegmond modify composer.json like

```
// First we want to change the version number to the targets branch name, prefixed with “dev-”, like so:
 "require": {
    "omz13/kirby3-xmlsitemap": "dev-master",
  },
// then tell composer where to pull 'master' from  
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/ceesvanegmond/kirby3-xmlsitemap"
    }
  ],
```

be mindful: off course you loose the sync to the versions on omz13 package!

**Comment by macx** [comment]
@b0rt  Don't care about losing the sync: The last commit was 2019, it's dead.

**Review by macx — APPROVED** [review]

**Pull request closed without merging**
